language: android

android:
    components:
        - build-tools-20.0.0
        - android-19

# whitelist
branches:
  only:
    - /^.*$/

env:
  matrix:
    - TERM=dumb

script: ./gradlew build jacocoTestReport --stacktrace

after_success:
    - ./gradlew jacocoRootReport coveralls --stacktrace
