language: java
jdk: oraclejdk7

# whitelist
branches:
  only:
    - /^.*$/

env:
  matrix:
    - TERM=dumb

script: ./gradlew build jacocoTestReport

after_success:
    - ./gradlew jacocoRootReport coveralls